import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { Check, CheckCircleIcon, X } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Temly",
  description: "Generated by create next app",
  icons: {
    icon: "/Temly.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased font-sans`}
      >
        {children}
        <Toaster

          toastOptions={{
            classNames: {
              success: "!bg-green-800 !border !border-green-600 !text-green-100 [&_*]:!font-semibold",
              description: "!text-green-100",
              error: "!bg-red-800 !border-1 !border-red-600 !text-white [&_*]:!font-semibold",
            },
          }}
        />
      </body>
    </html>
  );
}
